# Basics of Numpy module

## Import the numpy module

In [1]:
import numpy as np

## Numpy array creation

*Syntax* : `np.array(array)`

In [2]:
a=np.array([2,-1,0,5,-3,7])  # simple integer ndarray
a

array([ 2, -1,  0,  5, -3,  7])

In [3]:
b=np.array([2.03,-1.92,5.22,0.0739]) # simple float ndarray
b

array([ 2.03  , -1.92  ,  5.22  ,  0.0739])

In [4]:
c=np.array([[2.03,-1.92],[5.22,0.0739]]) # two dimensional float array
c

array([[ 2.03  , -1.92  ],
       [ 5.22  ,  0.0739]])

**Conversion of list to ndarray**

*Syntax* : `np.asarray(list)`

In [5]:
lst=[3,-2,0,1,8,5] # list creation
np.asarray(lst) # list conversion to ndarray

array([ 3, -2,  0,  1,  8,  5])

**Creation of array with certain interval**

*Syntax* : `np.arange(start,stop,step)`

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
d=np.arange(1,5,0.5)
d

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

*Syntax* : `np.linspace(start,stop,num,endpoint)`

In [8]:
e=np.linspace(-5,5,50) # endpoint=True by default
e

array([-5.        , -4.79591837, -4.59183673, -4.3877551 , -4.18367347,
       -3.97959184, -3.7755102 , -3.57142857, -3.36734694, -3.16326531,
       -2.95918367, -2.75510204, -2.55102041, -2.34693878, -2.14285714,
       -1.93877551, -1.73469388, -1.53061224, -1.32653061, -1.12244898,
       -0.91836735, -0.71428571, -0.51020408, -0.30612245, -0.10204082,
        0.10204082,  0.30612245,  0.51020408,  0.71428571,  0.91836735,
        1.12244898,  1.32653061,  1.53061224,  1.73469388,  1.93877551,
        2.14285714,  2.34693878,  2.55102041,  2.75510204,  2.95918367,
        3.16326531,  3.36734694,  3.57142857,  3.7755102 ,  3.97959184,
        4.18367347,  4.3877551 ,  4.59183673,  4.79591837,  5.        ])

In [9]:
f=np.linspace(-5,5,50,endpoint=False) # notice in output that the stop point is not included.
f

array([-5. , -4.8, -4.6, -4.4, -4.2, -4. , -3.8, -3.6, -3.4, -3.2, -3. ,
       -2.8, -2.6, -2.4, -2.2, -2. , -1.8, -1.6, -1.4, -1.2, -1. , -0.8,
       -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,
        1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,
        3.8,  4. ,  4.2,  4.4,  4.6,  4.8])

*Syntax* : `np.logspace(start,stop,num,endpoint=True,base=10)`

In [10]:
g=np.logspace(0.1,1,10)
g

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [11]:
10**0.1 # give the 1st element of the given array

1.2589254117941673

In [12]:
10**0.2 # give the 2st element of the given array

1.5848931924611136

### Change the dimension of array

*Syntax* : `ndarray.reshape(shape)`

In [13]:
d.reshape(2,4)

array([[1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5]])

In [14]:
d.reshape(2,2,2)

array([[[1. , 1.5],
        [2. , 2.5]],

       [[3. , 3.5],
        [4. , 4.5]]])

*Syntax* : `np.zeros(shape)`

In [15]:
np.zeros(5) # 1d ndarray with zeros

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,2)) # 2d array with 5 rows

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

*Syntax* : `np.ones(shape)`

In [17]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

*Syntax* : `np.full(shape,p)`

In [18]:
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

*Syntax* : `np.identity(n)` or `np.eye(n)`

n : number of rows (or columns) of the square matrix

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

*Syntax* : `np.tril(list or ndarray,k=0)`

In [21]:
h=[[3,-1,0],[7,-2,3],[5,-3,1]] # 3d list
l=np.tril(h) # gives a lower triangular matrix
l

array([[ 3,  0,  0],
       [ 7, -2,  0],
       [ 5, -3,  1]])

In [22]:
i=[[3,-1,0],[7,-2,3],[5,-3,1],[3,-2,7]]
np.tril(i)

array([[ 3,  0,  0],
       [ 7, -2,  0],
       [ 5, -3,  1],
       [ 3, -2,  7]])

In [23]:
np.tril(i,-1)

array([[ 0,  0,  0],
       [ 7,  0,  0],
       [ 5, -3,  0],
       [ 3, -2,  7]])

*Syntax* : `np.triu(list or ndarray,k=0)`

In [24]:
np.triu(h)

array([[ 3, -1,  0],
       [ 0, -2,  3],
       [ 0,  0,  1]])

In [25]:
np.triu(i,-1)

array([[ 3, -1,  0],
       [ 7, -2,  3],
       [ 0, -3,  1],
       [ 0,  0,  7]])

### Discretization of n-dimensional space

_One simple 2d mesh for $0\leq x\leq 0.4$ and $0\leq y\leq 0.9$._

In [26]:
x=np.arange(0,0.5,0.1)
y=np.arange(0,1,0.1)
X,Y=np.meshgrid(x,y)

In [27]:
X

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0. , 0.1, 0.2, 0.3, 0.4]])

In [28]:
Y

array([[0. , 0. , 0. , 0. , 0. ],
       [0.1, 0.1, 0.1, 0.1, 0.1],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.3, 0.3, 0.3, 0.3, 0.3],
       [0.4, 0.4, 0.4, 0.4, 0.4],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [0.6, 0.6, 0.6, 0.6, 0.6],
       [0.7, 0.7, 0.7, 0.7, 0.7],
       [0.8, 0.8, 0.8, 0.8, 0.8],
       [0.9, 0.9, 0.9, 0.9, 0.9]])

## Numpy array manipulation

*Syntax* : `np.concatenate(a1,a2,...,an,axis=0)`

In [29]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6]])
j=np.concatenate((arr1,arr2),axis=0)
j

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.concatenate((arr1,arr2.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

*Syntax* : `np.split(array,indices,axis=0)`

In [31]:
np.split(d,2)

[array([1. , 1.5, 2. , 2.5]), array([3. , 3.5, 4. , 4.5])]

In [32]:
np.split(d,[1,3,4])

[array([1.]), array([1.5, 2. ]), array([2.5]), array([3. , 3.5, 4. , 4.5])]

*Syntax* : `np.delete(array,indices,axis=None)`

In [33]:
np.delete(lst,3) # 4th element from left will be removed

array([ 3, -2,  0,  8,  5])

In [34]:
np.delete(h,2,0) # 2nd array will be removed

array([[ 3, -1,  0],
       [ 7, -2,  3]])

In [35]:
np.delete(h,2,1) # 2nd column elements will be removed.

array([[ 3, -1],
       [ 7, -2],
       [ 5, -3]])

*Syntax* : `np.insert(array,indices,values,axis=None)`

In [36]:
np.insert(lst,1,5) # insert 5 at position 1

array([ 3,  5, -2,  0,  1,  8,  5])

In [37]:
np.insert(h,2,5) # ndarray will be flattened(axis=None) and 5 will be inserted at position 2

array([ 3, -1,  5,  0,  7, -2,  3,  5, -3,  1])

In [38]:
np.insert(h,2,[5,3,-1],axis=0)

array([[ 3, -1,  0],
       [ 7, -2,  3],
       [ 5,  3, -1],
       [ 5, -3,  1]])

In [39]:
np.insert(h,2,4,axis=1)

array([[ 3, -1,  4,  0],
       [ 7, -2,  4,  3],
       [ 5, -3,  4,  1]])

*Syntax* : `np.append(array,values,axis=None)`

In [40]:
q=np.append(lst,7)
q

array([ 3, -2,  0,  1,  8,  5,  7])

In [41]:
r=np.append(lst,[5,6])
r

array([ 3, -2,  0,  1,  8,  5,  5,  6])

In [42]:
k=np.append(h,-5) # the array is flattend when the new value is appended
k

array([ 3, -1,  0,  7, -2,  3,  5, -3,  1, -5])

In [43]:
m=np.append(h,[[-9,0,1]],axis=0)
m

array([[ 3, -1,  0],
       [ 7, -2,  3],
       [ 5, -3,  1],
       [-9,  0,  1]])

In [44]:
np.append(h,[[-9],[0],[1]],axis=1)

array([[ 3, -1,  0, -9],
       [ 7, -2,  3,  0],
       [ 5, -3,  1,  1]])

*Syntax* : `np.flip(array,axis)`

In [45]:
np.flip(h,0)

array([[ 5, -3,  1],
       [ 7, -2,  3],
       [ 3, -1,  0]])

In [46]:
np.flip(h,1)

array([[ 0, -1,  3],
       [ 3, -2,  7],
       [ 1, -3,  5]])

In [47]:
np.flip(h[2],0)

array([ 1, -3,  5])

**Slicing ndarray**

*Syntax* : `array[start:end:step]`

In [48]:
k

array([ 3, -1,  0,  7, -2,  3,  5, -3,  1, -5])

In [49]:
k[:]

array([ 3, -1,  0,  7, -2,  3,  5, -3,  1, -5])

In [50]:
k[::]

array([ 3, -1,  0,  7, -2,  3,  5, -3,  1, -5])

In [51]:
p=k[2:8:2]
p

array([ 0, -2,  5])

In [52]:
k[::-1]

array([-5,  1, -3,  5,  3, -2,  7,  0, -1,  3])

In [53]:
h[:2:]

[[3, -1, 0], [7, -2, 3]]

**Accumulation of ndarrays**

*Syntax* : `np.hstack(tuples)`

In [54]:
tup1=[[1.2,1.3,1.4],[-2.1,-2.2,-2.3],[3.3,3.4,3.5]]
tup2=[[-4.3,-4.4],[5.1,5.2],[-6.2,-6.3]]
np.hstack((tup1,tup2)) # 3x5 array willbe produced

array([[ 1.2,  1.3,  1.4, -4.3, -4.4],
       [-2.1, -2.2, -2.3,  5.1,  5.2],
       [ 3.3,  3.4,  3.5, -6.2, -6.3]])

*Syntax* : `np.vstack(tuples)`

In [55]:
tup3=[[-4.3,4.4,-4.5],[5.1,5.2,5.3]]
np.vstack((tup1,tup3))

array([[ 1.2,  1.3,  1.4],
       [-2.1, -2.2, -2.3],
       [ 3.3,  3.4,  3.5],
       [-4.3,  4.4, -4.5],
       [ 5.1,  5.2,  5.3]])

**Vectorize a function**

*Syntax* : `np.vectorize(func)`

In [56]:
def fnc1(x):
    if x>=5:
        res=5
    elif x<=-5:
        res=-5
    else:
        res=0
    return res

def fnc2(x,y):
    if x>y:
        res=x-y
    else:
        res=x+y
    return res

vec_fnc1=np.vectorize(fnc1)
vec_fnc2=np.vectorize(fnc2)

In [57]:
vec_fnc1([-6,-1,3,7,11])

array([-5,  0,  0,  5,  5])

In [58]:
vec_fnc2([-1,0,1,2,3],1)

array([0, 1, 2, 1, 2])

**Flatten ndarray**

*Syntax* : `ndarray.ravel()`

In [59]:
m.ravel() # flatten ndarray to 1d array

array([ 3, -1,  0,  7, -2,  3,  5, -3,  1, -9,  0,  1])

In [60]:
m.ndim # return the dimension of ndarray

2

In [61]:
k.shape # return structurewise dimension of ndarray

(10,)

In [62]:
c.shape

(2, 2)

In [63]:
m.tolist() # convert ndarray to native list

[[3, -1, 0], [7, -2, 3], [5, -3, 1], [-9, 0, 1]]

In [64]:
m.copy() # return a copy of the ndarray

array([[ 3, -1,  0],
       [ 7, -2,  3],
       [ 5, -3,  1],
       [-9,  0,  1]])

In [65]:
m.T # return the transpose of ndarray

array([[ 3,  7,  5, -9],
       [-1, -2, -3,  0],
       [ 0,  3,  1,  1]])

In [66]:
m.diagonal() # return the diagonal of ndarray

array([ 3, -2,  1])

In [67]:
c.round() # return each element in rounded decimal

array([[ 2., -2.],
       [ 5.,  0.]])

In [68]:
m.max() # return maximum value

7

In [69]:
m.min() # return minimum value

-9

In [70]:
k.mean()

0.8

In [71]:
k.sum()

8

In [72]:
k.prod() # return the product of array elements

0

In [73]:
c.prod()

-1.5035303807999993

In [74]:
k.var() # return the varience

12.560000000000002

In [75]:
np.median(k) # return the median value of array elements

0.5

In [76]:
m.trace() # return the sum of diagonal elements

2

In [77]:
k.sort()
k

array([-5, -3, -2, -1,  0,  1,  3,  3,  5,  7])

In [78]:
arr1.dot(arr2.T)

array([[17],
       [39]])

In [79]:
k.astype(int)

array([-5, -3, -2, -1,  0,  1,  3,  3,  5,  7])

In [80]:
k.astype(str)

array(['-5', '-3', '-2', '-1', '0', '1', '3', '3', '5', '7'], dtype='<U11')

In [81]:
o=np.array([1.0,2.0,3.0,4.0,5.0])
o.fill(5.39)
o

array([5.39, 5.39, 5.39, 5.39, 5.39])

In [82]:
m.flatten()

array([ 3, -1,  0,  7, -2,  3,  5, -3,  1, -9,  0,  1])

In [83]:
cplx=2.6+3.5j
np.conj(cplx)

(2.6-3.5j)

In [84]:
q

array([ 3, -2,  0,  1,  8,  5,  7])

In [85]:
np.diff(r)

array([-5,  2,  1,  7, -3,  0,  1])

*Syntax* : `np.argmax/argmin(array,axis=None,out=None)`

In [86]:
np.argmax(k)

9

In [87]:
np.argmin(k)

0

In [88]:
np.argmax(m,axis=0)

array([1, 3, 1], dtype=int64)

In [89]:
np.argmin(m,axis=1)

array([1, 1, 1, 0], dtype=int64)

## Pre-defined functions and constants

In [90]:
pol=np.poly1d([2,-3,1]) # defines a polynomial 2x^2-3x+1
pol(2.3)

4.679999999999999

In [91]:
np.floor(7.15)

7.0

In [92]:
np.ceil(-5.81)

-5.0

In [93]:
np.exp(2.3701)

10.698462076828207

In [94]:
np.sin(k)

array([ 0.95892427, -0.14112001, -0.90929743, -0.84147098,  0.        ,
        0.84147098,  0.14112001,  0.14112001, -0.95892427,  0.6569866 ])

In [95]:
np.cos(k)

array([ 0.28366219, -0.9899925 , -0.41614684,  0.54030231,  1.        ,
        0.54030231, -0.9899925 , -0.9899925 ,  0.28366219,  0.75390225])

In [96]:
np.tan(k)

array([ 3.38051501,  0.14254654,  2.18503986, -1.55740772,  0.        ,
        1.55740772, -0.14254654, -0.14254654, -3.38051501,  0.87144798])

In [100]:
np.log(15.9264)

2.767978109682098

In [101]:
np.inf # positive infinty

inf

In [103]:
np.NINF # negative infinity

-inf

In [104]:
np.pi # value of pi

3.141592653589793

In [106]:
np.e # value of e

2.718281828459045

## Algebraic and logic operations on Ndarray

*Syntax* : `np.add/subtract/multiply(ndarray,number/ndarray)`

In [110]:
u=np.add(k,3)
u

array([-2,  0,  1,  2,  3,  4,  6,  6,  8, 10])

In [108]:
k+3

array([-2,  0,  1,  2,  3,  4,  6,  6,  8, 10])

In [111]:
np.add(k,u)

array([-7, -3, -1,  1,  3,  5,  9,  9, 13, 17])

In [113]:
np.subtract(k,1)

array([-6, -4, -3, -2, -1,  0,  2,  2,  4,  6])

In [114]:
np.subtract(k,u)

array([-3, -3, -3, -3, -3, -3, -3, -3, -3, -3])

In [115]:
np.multiply(k,2)

array([-10,  -6,  -4,  -2,   0,   2,   6,   6,  10,  14])

In [116]:
np.multiply(k,u)

array([10,  0, -2, -2,  0,  4, 18, 18, 40, 70])

*Syntax* : `np.all/any(array,axis=None)`

In [118]:
np.all(a)

False

In [119]:
np.all(k)

False

In [120]:
np.all([-1,4,5])

True

In [122]:
np.any([-1,4,5])

True

In [123]:
np.any(a)

True

In [124]:
np.any(k)

True

*Syntax* : `np.isfinite(array)`

In [125]:
np.isfinite(k)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [126]:
np.isfinite(np.inf)

False

**The End**