In [1]:
import numpy as np

**Numpy ndarray declaration**

In [2]:
# matrices
a=np.array([[-2,1],[0,3]]) 
b=np.array([[-3,2],[0,1]])
# vectors
u=np.array([2,-3])
v=np.array([-2,1])
r=np.array([2,-3,-1])
s=np.array([-1,2,3])

**Vector Operations**

In [3]:
u.dot(v)

-7

In [4]:
np.dot(u,v)

-7

In [5]:
np.inner(u,v)

-7

In [6]:
np.vdot(u,v)

-7

In [7]:
u.dot(u)

13

In [8]:
a.dot(u) # matrix and vector product, numpy attribute

array([-7, -9])

In [9]:
np.cross(r,s) # vector cross product

array([-7, -5,  1])

**Matrix Operation**

In [10]:
np.dot(a,u)

array([-7, -9])

In [11]:
u+b.dot(v)

array([10, -2])

In [12]:
a.dot(b)

array([[ 6, -3],
       [ 0,  3]])

In [13]:
a*b

array([[6, 2],
       [0, 3]])

In [14]:
a**3

array([[-8,  1],
       [ 0, 27]], dtype=int32)

**Declaration of numpy matrix**

In [15]:
a=np.matrix('[6,2,3]') # row matrix
b=np.matrix('[4;5;9]') # column matrix
x=np.matrix([[2,-1],[3,-2]])
y=np.matrix([[-2,1],[4,-3]])

**Vector Operations with np.matrix()**

In [16]:
a*b

matrix([[61]])

In [17]:
a.dot(b)

matrix([[61]])

In [18]:
np.dot(a,b)

matrix([[61]])

In [19]:
a.transpose()

matrix([[6],
        [2],
        [3]])

In [20]:
np.transpose(a)

matrix([[6],
        [2],
        [3]])

In [21]:
a

matrix([[6, 2, 3]])

**Matrix operations with np.matrix()**

In [22]:
b*a

matrix([[24,  8, 12],
        [30, 10, 15],
        [54, 18, 27]])

In [23]:
np.dot(b,a)

matrix([[24,  8, 12],
        [30, 10, 15],
        [54, 18, 27]])

In [24]:
b.dot(a)

matrix([[24,  8, 12],
        [30, 10, 15],
        [54, 18, 27]])

In [25]:
x*y

matrix([[ -8,   5],
        [-14,   9]])

In [26]:
x**2

matrix([[1, 0],
        [0, 1]])

In [27]:
y**(-1)

matrix([[-1.5, -0.5],
        [-2. , -1. ]])

In [28]:
y*y**(-1)

matrix([[1., 0.],
        [0., 1.]])

In [29]:
y**(-3)

matrix([[ -7.375,  -2.875],
        [-11.5  ,  -4.5  ]])

**Matrix operations using numpy.linalg**

In [30]:
import numpy.linalg as la

In [31]:
a=np.array([[-2,1],[0,3]])
la.det(a)

-6.0

In [32]:
la.norm(a)

3.7416573867739413

In [33]:
la.matrix_rank(a)

2

In [34]:
lmb,x=la.eig(a)

In [35]:
lmb # eigen values

array([-2.,  3.])

In [36]:
x # eigen vectors

array([[1.        , 0.19611614],
       [0.        , 0.98058068]])

**Examples**

In [37]:
# numpy determinant exmaple 01
th=[-np.pi,-np.pi/2,0,np.pi/2,np.pi]
for i in th:
    a=np.array([[np.cos(i),1,0],[1,2*np.cos(i),1],[0,1,2*np.cos(i)]])
    lhs=la.det(a)
    rhs=np.cos(3*i)
    print("%.3e,%.3e"%(lhs,rhs))

-1.000e+00,-1.000e+00
-1.837e-16,-1.837e-16
1.000e+00,1.000e+00
-1.837e-16,-1.837e-16
-1.000e+00,-1.000e+00


$u=3i+6j+9k , v=-2i+3j+k$

In [38]:
# Angle between two vectors
u=np.array([3,6,9])
v=np.array([-2,3,1])
uv=np.vdot(u,v)
u_mag,v_mag=(np.vdot(u,u))**0.5,(np.vdot(v,v))**0.5
th=np.arccos(uv/(u_mag*v_mag))
print("Angle in degree = %.4f"% np.rad2deg(th))

Angle in degree = 60.0000


$a=2i+j-k,b=i+3j-2k$

In [39]:
# Unit vector perpendicular to both of two given vectors
a=np.array([2,1,-1])
b=np.array([1,3,-2])
axb=np.cross(a,b)
axb_mag=(np.vdot(axb,axb))**0.5
u_vec=axb*(1/axb_mag) # multiply each element by (1/axb_mag)
u_ax=['i','j','k'] # array for the names of unit vectors along axes
print("Unit perpendicular vector =",end="")
for i in range(len(u_vec)-1):
    print("%.3f%s"%(u_vec[i],u_ax[i]),end="+")
    print("%.3f%s"%(u_vec[i+1],u_ax[i+1]))

Unit perpendicular vector =0.169i+0.507j
0.507j+0.845k


$a=2i-3j+4k,b=i+2j-k,c=3i-j+2k$

In [40]:
a=np.array([2,-3,4])
b=np.array([1,2,-1])
c=np.array([3,-1,2])

bxc=np.cross(b,c)
abxc=a.dot(bxc) # symbolic dot product
abc=np.array([a,b,c]) # matrix from a,b,c
det_abc=la.det(abc)
print("a.(bxc)=%0.4f,det([a,b,c])=%0.4f"%(abxc,det_abc))

a.(bxc)=-7.0000,det([a,b,c])=-7.0000


$f(A)=3-2A^2-A^3-5A^4+A^6$

In [41]:
# function of matrix
coef=[3,0,-2,-1,-5,0,1] # co-efficient array
# Using numpy.array()
a=np.array([[1,2**0.5],[-2**0.5,-1]])
i=np.eye(2)
sa=np.zeros(2)
ta=i

for k in range(len(coef)):
    ta=ta.dot(a) # symbolicmatrix power in iterative way
    sa=sa+coef[k]*ta # symbolic matrix operation
print("Result=")
print(sa)

Result=
[[-2.00000000e+00 -1.41421356e+00]
 [ 1.41421356e+00  3.99680289e-15]]


In [42]:
# Using numpy.matrix()
a=np.array([[1,2**0.5],[-2**0.5,-1]])
sa=np.zeros(2)
for i in range(len(coef)):
    sa=sa+a**i*coef[i] # symblic matrix power directly
print("Result=")
print(sa)

Result=
[[ -4.         -15.82842712]
 [-10.17157288  -2.        ]]


In [43]:
# Symmetric transformation of matrix
s=np.array([[1,2],[3,4]])
## Using np.array()

u=np.array([[1,1],[1,-1]])
u=(0.5**0.5)*u
u_inv=la.inv(u)
usu_inv=(u.dot(s)).dot(u_inv)
print('usu^-1 for np.array()=')
print(usu_inv)

# Using np.matrix()
u=np.matrix([[1,1],[1,-1]])
u=(0.5**0.5)*u
usu_inv=u*s*u**(-1) # symbolic matrix operation
print('usu^-1 for np.matrix()=')
print(usu_inv)

usu^-1 for np.array()=
[[ 5.00000000e+00 -1.00000000e+00]
 [-2.00000000e+00 -2.22044605e-16]]
usu^-1 for np.matrix()=
[[ 5.00000000e+00 -1.00000000e+00]
 [-2.00000000e+00 -2.22044605e-16]]


In [44]:
# Principle moments and principal axes of a rigid body
i=np.array([[4,-1,-1],[-1,4,-1],[-1,-1,4]])
pm,pa=la.eig(i)
pa=pa.T
print("Principle moments and principle axes are")
for i in range(len(pm)):
    print(pm[i],pa[i])

Principle moments and principle axes are
5.0 [ 0.81649658 -0.40824829 -0.40824829]
1.9999999999999996 [-0.57735027 -0.57735027 -0.57735027]
5.0 [ 0.47168785 -0.81302061  0.34133277]
